export { default as Slope } from './Slope'
export { default as Phantom } from './Phantom'
export { default as Solflare } from './Solflare'
export { default as TrustWallet } from './TrustWallet'
export { default as TokenPocket } from './TokenPocket'
export { default as BitgetWallet } from './BitgetWallet'
export { default as WalletConnect } from './WalletConnect'
export { default as CoinbaseWallet } from './CoinbaseWallet'
