version: '3.8'

services:
  node:
    build:
      context: .
    container_name: multiplechain-js
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    init: true
    tty: true

volumes:
  node_modules: 