packages:
    - 'packages/*'
    - 'packages/networks/*'

minimumReleaseAgeExclude:
    - '@multiplechain/*'

allowBuilds:
    '@reown/appkit': false
    bigint-buffer: true
    bufferutil: false
    esbuild: true
    keccak: true
    secp256k1: true
    utf-8-validate: false
